name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: >
      Build Wheel
      (${{ matrix.platform.os }}, ${{ matrix.platform.name }}, ${{ matrix.platform.arch }})
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
        - os: ubuntu-latest
          name: manylinux
          arch: aarch64
        - os: ubuntu-latest
          name: manylinux
          arch: x86_64
        - os: macos-latest
          name: macosx
          arch: universal2

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.10.2
        env:
          CIBW_ARCHS_LINUX: x86_64 aarch64
          # CIBW_ARCHS_MACOS: x86_64 arm64
          CIBW_ARCHS_MACOS: universal2
          CIBW_BUILD: 'cp*-${{ matrix.platform.name }}_${{ matrix.platform.arch }}'
          CIBW_TEST_SKIP: "*-macosx_arm64 *-macosx_universal2:arm64"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
