name: Build

on: [push, pull_request]

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache Clips
      id: cache-clips
      uses: actions/cache@v3
      with:
        path: clips_source
        key: ${{ runner.os }}-${{ hashFiles('Makefile') }}
    - name: Build Clips
      if: steps.cache.outputs.cache-hit != 'true'
      run: make clips
    - name: Install Clips
      run: sudo make install-clips
    - name: Test
      run: >
        pip install -U pip setuptools pytest &&
        pip install -e . &&
        LD_LIBRARY_PATH=$LD_LIBRARY_PATH:clips_source pytest -v

  build_wheels:
    needs: validate
    # if: ${{ github.ref == 'refs/heads/master' }}
    name: >
      Build Wheel
      (${{ matrix.platform.os }}, ${{ matrix.platform.name }}, ${{ matrix.platform.arch }})
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
        - os: ubuntu-latest
          name: manylinux
          arch: aarch64
        - os: ubuntu-latest
          name: manylinux
          arch: x86_64
        - os: macos-latest
          name: macosx
          arch: universal2

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.10.2
        env:
          CIBW_ARCHS_LINUX: x86_64 aarch64
          CIBW_ARCHS_MACOS: universal2
          CIBW_BUILD: 'cp*-${{ matrix.platform.name }}_${{ matrix.platform.arch }}'
          CIBW_TEST_SKIP: "*-macosx_arm64 *-macosx_universal2:arm64"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
